name: Build
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "check is EXPO_TOKEN exists"
        env:
          super_secret: ${{ secrets.EXPO_TOKEN }}
        if: ${{ env.super_secret == '' }}
        run: 'echo "echo the secret \"EXPO_TOKEN\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it'

      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build app
        run: eas build --non-interactive --platform all
